# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to an existing IKS cluster

name: Build and Deploy to IKS

# Execute on every push to the default branch. Merging a pull request counts as a push.
on:
  push:
    branches:
      - test-json

jobs:
  build-push-deploy-job:
    runs-on: ubuntu-latest
    name: A job to download and log into ibmcloud cli
    steps:
      - uses: actions/checkout@v2
        env:
          VCAP_LOCAL: ${{ secrets.VCAP_LOCAL }}      
      - name: Set environment variables
        run: |
          echo "$VCAP_LOCAL" >> ./vcap-local.json
          cat vcap-local.json
          echo "$VCAP_LOCAL"
          echo $VCAP_LOCAL
