# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to an existing IKS cluster

name: Build and Deploy to IKS

# Execute on every push to the default branch. Merging a pull request counts as a push.
on:
  push:
    branches:
      - test-json

jobs:
  build-push-deploy-job:
    runs-on: ubuntu-latest
    name: A job to download and log into ibmcloud cli
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          echo ${{ secrets.VCAP_LOCAL }} >> ./web/api/vcap-local.json
          echo REACT_APP_MAPBOX_ACCESS_TOKEN=${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }} >> ./web/client/.env.local
     
     # Turnstyle ensures that this job only runs one at a time in this repository
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: call-for-code/build-push-deploy@main
        with:
          cloud-api-key: ${{ secrets.IBM_CLOUD_API_KEY }}
          cloud-resource-group: OpenEEW-Infra
          cloud-region: us-south
          deployment-name: openeew-dashboard
          github-sha: ${{ github.sha }}
          icr-namespace: ${{ secrets.ICR_NAMESPACE }}
          image-name: dashboard
          k8s-cluster-name: ${{ secrets.K8S_CLUSTER_NAME }}
          k8s-cluster-namespace: ${{ secrets.K8S_CLUSTER_NAMESPACE }}
          registry-hostname: us.icr.io
